version: '3'

services:
  loadbalancer:
    image: traefik
    container_name: keycloak-loadbalancer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./loadbalancer/traefik.toml:/etc/traefik/traefik.toml:ro"
    command: -c /etc/traefik/traefik.toml
    networks:
      - keycloak
    depends_on: 
      - keycloak1
      - keycloak2

  mysql_jdbcping:
    image: mysql:5.7.25
    networks:
      keycloak: { aliases: ["mysql.keycloak", "mysql_jdbcping"] }
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 3s
      timeout: 5s
      retries: 100
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"

  keycloak1:
    container_name: keycloak1
    build:
      dockerfile: Dockerfile
      context: ./
    environment: &keycloak_env
      DB_ADDR: mysql_jdbcping
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_VENDOR: mysql
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JDBCPING_DB_USER: keycloak
      JDBCPING_DB_PASSWORD: keycloak
      JDBCPING_DB_DATABASE: keycloak
      JDBCPING_DB_HOST: mysql_jdbcping
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_NODE_HOSTNAME: "keycloak1"
      CACHE_OWNERS: 2
    depends_on:
      - mysql_jdbcping
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefix:/auth"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Host:localhost"
      - "traefik.backend=keycloak"
      - "traefik.backend.healthcheck.path=/auth/realms/master/health/check"
    networks:
      keycloak: { aliases: ["node1.keycloak", "keycloak1"] }

  keycloak2:
    container_name: keycloak2
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      <<: *keycloak_env
      JGROUPS_NODE_HOSTNAME: "keycloak2"
    depends_on:
      - mysql_jdbcping
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefix:/auth"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Host:localhost"
      - "traefik.backend=keycloak"
      - "traefik.backend.healthcheck.path=/auth/realms/master/health/check"
    networks:
      keycloak: { aliases: ["node2.keycloak", "keycloak2"] }

networks:
  keycloak: