version: '3'

services:
  loadbalancer:
    ports:
      - "80:80"
      - "1337:8080"
  mysql_jdbcping:
    ports:
      - "3306:3306"
  keycloak1:
    ports:
      - "8081:8080"
      - "7601:7600" # jgroups
  keycloak2:
    ports:
      - "8082:8080"
      - "7602:7600" # jgroups